name: test-workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-pipeline:
    runs-on: 'bash'
    steps:
      - name: Clean Workspace Path
        run: |
           echo "Cleaning Build Workspace"
           rm -Rf "{{ github.workspace }}"

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
           ref: ${{ github.event.pull_request.head.ref }}

      - name: Test Python3
        run: |
           python3 hello.py

      - name: Test Custom Variable
        run: |
           echo "Custom Variable => ${{ vars.T_VAR }}"


  build-app:
    runs-on: 'bash'
    steps:
      - name: Clean Workspace Path
        run: |
           echo "Cleaning Build Workspace"
           rm -Rf "{{ github.workspace }}"

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64

