name: test-workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-pipeline:
    runs-on: 'base'
    steps:
      - name: Clean Workspace Path
        run: |
           echo "Cleaning Build Workspace"
           rm -Rf "{{ github.workspace }}"

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
           ref: ${{ github.event.pull_request.head.ref }}

      - name: Test Python3
        run: |
           python3 hello.py
